" load plugins
so ~/dotfiles/config/vim/plugins.vimrc

colorscheme molokai

set showcmd
set number
set encoding=utf-8

syntax on



" 1 tab == 4 spaces
set shiftwidth=4
set tabstop=4
" for bigger cmd line
set cmdheight=2

" Enable code folding
set foldmethod=indent
set foldlevel=99
" Enable folding with spacebar
nnoremap <space> za

set showmatch
set matchtime=10

" copy and paste
vmap <C-c> "+yi
vmap <C-x> "+c
vmap <C-v> c<ESC>"+p
imap <C-v> <ESC>"+pa

"toggle paste mode
set pastetoggle=<F3>

"fix color and blinking while matching brackets
hi MatchParen cterm=bold ctermbg=none ctermfg=red
let g:rainbow_active = 1
" Useful mappings for managing tabs
nnoremap <leader>tn :tabnew<CR>
nnoremap <leader>to :tabonly<CR>
nnoremap <leader>tc :tabclose<CR>
nnoremap <leader>tm :tabmove 
nnoremap <A-Left> :tabprevious<CR>                                                                            
nnoremap <A-Right> :tabnext<CR>
nnoremap <leader>Right :tabnext<CR>
" Fast saving
map <leader>w :w!<cr>

" Run program
map <leader>r :QuickRun<CR>

nnoremap <C-R> :term python % <CR>
" set ctermfg to desired line numbers colors and ctermbg to NONE for
" transparency
highlight LineNr term=bold cterm=NONE ctermfg=White ctermbg=NONE gui=NONE guifg=DarkGrey guibg=NONE

"set leader to , instead of default /
let mapleader = ','

" absolute width of netrw window
" let g:netrw_winsize = -28

" tree-view
" let g:netrw_liststyle = 3

" command to use sudo
cmap w!! %!sudo tee > /dev/null %

set backupdir=~/.vim/tmp/                   " for the backup files
set directory=~/.vim/tmp/                   " for the swap files

" sort is affecting only: directories on the top, files below
let g:netrw_sort_sequence = '[\/]$,*'

" open file in a new tab
let g:netrw_browse_split = 3

" Leader C is the prefix for code related mappîngs 
noremap <silent> <Leader>cc :TComment<CR>

" Leader F is for file related mappîngs (open, browse...) 
nnoremap <silent> <Leader>f :CtrlP<CR>
nnoremap <silent> <Leader>fm :CtrlPMRU<CR>

""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Ctrl B for buffer related mappings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
nnoremap <silent> <Leader>b :CtrlPBuffer<CR> " cycle between buffer
nnoremap <silent> <Leader>bb :bn<CR> "create (N)ew buffer
nnoremap <silent> <Leader>bd :bdelete<CR> "(D)elete the current buffer
nnoremap <silent> <Leader>bu :bunload<CR> "(U)nload the current buffer
nnoremap <silent> <Leader>bl :setnomodifiable<CR> " (L)ock the current buffer"

nnoremap <C-n> :NERDTreeToggle<CR>
nnoremap <F5> :UndotreeToggle<CR>

"Code settings
au BufNewFile,BufRead *.py
    \ set tabstop=4
    \| set softtabstop=4
    \| set shiftwidth=4
    \| set textwidth=79
    \| set expandtab
    \| set autoindent
    \| set fileformat=unix

au BufNewFile,BufRead *.js, *.html, *.css
    \ set tabstop=2
    \| set softtabstop=2
    \| set shiftwidth=2

highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter *.py,*.pyw  match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0


let g:quickrun_config = {
      \'*': {
      \'outputter/buffer/split': ':10split'},}

"reloads .vimrc -- making all changes active
nnoremap <silent> <Leader>v :source ~/.vimrc<CR>:PlugInstall<CR>:bdelete<CR>:exe ":echo 'vimrc reloaded'"<CR>
