### GENERAL
HISTSIZE=1000000
SAVEHIST=1000000
HISTFILE=~/.zsh_history
EDITOR=nvim
export ZSH="$HOME/.oh-my-zsh"
export PATH=$HOME/.local/bin:$HOME/tools/bin:$PATH

ZSH_THEME="aphrodite"

ZSH_TMUX_AUTOSTART=true

### OH-MY-ZSH SETTINGS
plugins=(
git
tmux
themes
web-search
vi-mode
)

source $ZSH/oh-my-zsh.sh

### ALIASES
alias pacsearch="pacman -Slq | fzf -m --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S"
alias yaysearch="yay -Slq | fzf -m --preview 'yay -Si {1}'| xargs -ro yay -S"
alias yayinstalledrm="yay -Qeq | fzf -m --preview 'yay -Qi {1}' | xargs -ro yay -Rs"
alias ls="lsd"
alias open="xdg-open"
alias top="bpytop"

### PLUGINS
source ~/dotfiles/config/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null

source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
#source /usr/share/zsh/plugins/zsh-vi-mode/zsh-vi-mode.plugin.zsh

function pokecheck()
{
	/usr/bin/brave "https://bulbapedia.bulbagarden.net/wiki/$1_(Pok%C3%A9mon)/Generation_VI_learnset#By_TM.2FHM"
}

