### GENERAL
HISTSIZE=1000000
SAVEHIST=1000000
HISTFILE=~/.zsh_history

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="aphrodite"

ZSH_TMUX_AUTOSTART=true

### OH-MY-ZSH SETTINGS
plugins=(
git
vi-mode
tmux
themes
)

source $ZSH/oh-my-zsh.sh


### PLUGINS
source ~/dotfiles/config/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
